---
title: "Skills"
---

I have worked on a range of topics in evolutionary genetics, but a common theme is investigating the link between genes and their environments in the relevant biological context.

I would highlight four key areas of expertise I have gained:

## Data analysis

-   I have more than **10 years experience of using R and Python** for data analysis almost every day, including interacting with both Git and high performance computing clusters.
-   The work I have most enjoyed has been those where conventional approaches run into difficulty, and the way forward has come by **approaching the problem from a different angle**. For example:
    -   [Speeding up paternity inference](https://github.com/ellisztamas/faps)
    -   Taking a quantitative, rather than categorical, approach to [investigating pleiotopy](https://github.com/ellisztamas/sintillate)
-   A strong focus on **robust, reproducible code**. See for example:
    -   Code repositories accompanying publications on [fitness components](https://github.com/ellisztamas/fecundity_components) or [virus resistance](https://github.com/ellisztamas/tumv_ms) *Arabidopsis thaliana*.
    -   The R and Python [packages](/software/) I have written to support my research.

## Large-scale field experiments

-   I have gained ample experience of planning, carrying out and harvesting **large-scale field experiments**.
    -   During my PhD I was involved and occasionally led a demographic survey of thousands of wild snapdragons
    -   I designed and led a large-scale pollination assay in the field.
    -   During my post-doctoral work on local adaptation in *Arabidopsis thaliana* I was responsible for organising six reciprocal transpant experiments involving hundreds of thousands of plants in two countries.
-   Key to this is an emphasis on **careful experimental design**:
    -   In my current position investigating methylation variation we suspected that there was cryptic confounding affecting our bisulphite sequencing data. Thanks to careful blocking and randomisation I was able to isolate the problem and refine subsequent data collection.

## Leadership and mentoring

-   I lead the organisation and experimental design of a European Research Council project on DNA methylation, liasing between multiple teams.
-   I have organised and led teams of volunteers in data collection for multiple large field experiments to strict deadlines.
-   I have initiated and led the organisation of three IST Austria PhD Symposia, as well as networking meetings for the Vienna evolutionary biology community.
-   I have assisted in the supervision of several PhD students in conjunction with principal investigators.
-   I set up a lab wiki to facilitate internal knowledge sharing.
-   Led a writing group of students and postdocs to improve each other’s writing skills.

## Clear communication

I take great satisfaction in presenting complex ideas clearly to non-experts:

-   Winner of the Vienna "Science Slam" 2013, presenting my research to the public.
-   Winner of the IST Austria "Best talk" for the internal seminar series 2014 for mixed audience of scientists.
-   My PhD thesis was nominated for "best thesis" in 2016