---
title: "Software"
---

I maintain several packages for R and Python related to analysing genetic data.

- **ibdpainting**: A tool to visually validate the ancestry of an individual by comparing SNP data to a panel of candidate parents. Have a look at:
  - The [Github repo](https://github.com/ellisztamas/ibdpainting)
  - A [snakemake pipeline](https://github.com/ellisztamas/ibdpainting_pipeline) implementing it.
  - [Examples](/assets/06_ibdpainting_results.html) of some of the patterns you might see.
- **psiotropy**: An R package for quantifying pleiotropy (the extent to which genes affect multiple traits).
  - [Preprint](https://doi.org/10.64898/2026.01.09.698568) explaining the method.
  - [GitHub repo](https://github.com/ellisztamas/psiotropy)
- **methlab**: A Python package meant to automate common tasks related to handling bisulphite sequence data. Have a look at:
  - The [GitHub repo](https://github.com/ellisztamas/methlab).
  - The [documentation](https://methlab.readthedocs.io/en/latest/).
- **Fractional Analysis of Sibships and Paternity** (FAPS): a Python package to jointly infer paternal and sibling relationships using for large SNP datasets. See the:
  - [Accompanying paper](/assets/pdfs/2018_FAPS_paper.pdf) with the details.
  - [GitHub repo](https://github.com/ellisztamas/faps)
  - [Documentation](https://fractional-analysis-of-paternity-and-sibships.readthedocs.io/en/latest/index.html), which includes extensive tutorials
-   [arghqtl](https://github.com/ellisztamas/arghqtl): Tools for plotting and downstream analysis of R/QTL objects in R. It is intended in particular for cases where there are many QTL models to compare, and one's first thought about how to plot them is 'AAAAARGH!'.
