---
title: "Peppa Pig episodes I'd like to see"
date: "2024-03-21"
---

Let us just say "corona-virus lockdown with a two-year-old".

This page is to commemorate the depths of my madness circa 2021.

## Shopping

Miss Rabbit is hospitalised with Covid-19, but since she seems to do more than half the jobs in the town, society promptly collapses.
Meanwhile, Daddy Pig stockpiles toilet roll, the prick, but then can't buy any food because Miss Rabbit also runs the shop.
Peppa learns a heartwarming lesson about who really generates value in the economy, and it's not her waste-of-oxygen of a father.

## Small boats

Despite having worked at the same school for decades, Madame Gazelle is denied Settled Status by the Home Office and is deported back to France.
With the playgroup closed, Grandma Pig and Grandpa Pig have to pick up the slack with child care, just as their fruit trees ripen and there is no migrant labour to help. Grandpa Pig realises the newspapers have lied to him about how easy Brexit would be, as political choices start affecting him personally.
He vows never to read the Telegraph again.

Back in France, Madame Gazelle finds herself craving a Gregg's Steak Bake, but is too ashamed to admit it.

## Suzy Sheep

Questions finally get asked about Suzy Sheep, such as why she keeps stabbing her best mate in the back, or that time she repeatedly suggested murdering two firefighters in the episode "Naughty Tortoise".
As the gang realise Suzy combines a disregard for anyone else's feelings with poor numerical skills (she's literally in Kindergarten to be fair), she is immediately tipped to replace Priti Patel as Home Secretary.

## Scabs

Peppa faces a moral dilemma when she realises that the muddy puddles she loves to jump in are potholes caused by a decade of chronic underfunding under Tory austerity.
She joins the Labour Party as a grassroots activist to try and get things changed.
Alas, the staff at the Guardian have already flipped the coin to decide Whose Side They Are On that week, and Mr Elephant publishes a think piece pointing out that pigs aren't kosher.
Meanwhile, Daddy Pig is invited by his uni mate David to a social event at the local conservative club. He doesn't say what happened, but returns looking... haunted.

## Jordan

Pedro Pony (let's be honest, who else was it gonna be?) stumbles across a Jordan Peterson video on YouTube, and spends more and more time on alt-right websites.
Things finally blows up when he calls Daddy Pig a 'retarded libcuck' at Rebecca Rabbit's birthday party.
Undeterred, he pens a blog post explaining why science proves that ponies have higher IQs than pigs.
Despite being a rambling stream of consciousness by a pre-schooler, even Madame Gazelle has to agree that it is at least more coherent than "12 Rules for Life".

## Candy Cat

Candy Cat finally gets an episode to herself, because isn't it weird that she's meant to be one of Peppa's friends but they never invite her to stuff or let her have any lines?
Is it because her family is from Glasgow, and Peppa and friends are a bit racist?
Or could it be that she's a selfish lazy cat who doesn't care if you live or die?
Either way, it backfires, as Candy spends the whole episode sleeping or licking her backside.

## Mammals

After the episode "The Zoo", Mrs Crocodile opens Peppa's eyes to the fact that she is the only non-mammal Peppa ever spoken to; there are plenty of birds and reptiles in other episodes, but they are kept for amusement by the mammals and never engaged with.
Are they not conscious beings?
Do the mammals just see them as sub-mammal and ignore them?
It turns out that Mrs Crocodile is quite the firebrand, forcing Peppa to ask herself: do I live in a slave state?

## Yewtree

During a trip to the museum Peppa and the George learn about the Hundred-Years War. Mr Rabbit explains the importance of the longbow in crucial battles like Agincourt and Poiters, and how this technology rested upon the suppleness of the wood of the yew tree. In an ironic twist of fate, Grampy Rabbit is finally busted by Operation Yewtree.

## The Longest Game

It's well known that Tiddles "the naughty" Tortoise loves climbing trees, as he keeps doing so in multiple episodes. Finally, we see the story from Tiddles' perspective.

The episode begins with a grim-faced Tiddles atop a tall, leafless, tree on a bleak Autumn day. The grey lens filter makes it clear what he has in mind: Tiddles wants to jump, and end his suffering. The scene cuts to a bright woodland scene,  where a much younger Tiddles frolics in the sun. Suddenly there's a cry of "aww, 'e's loveleh", and a furry, grasping, (and let's be honest) disproportionately large, rodent paw swoops in and pulls him away from everything he's known.

Dr Hamster is his mistress now. His life is one of unending tedium trapped in a glass cage. The persistent droning of the doctor's moronic voice becomes the white noise of his universe as she attends to whatever fatuous non-emergencies she's dealing with that day. His repeated attempts to end it all by hurling himself from a tree are thwarted by a series of well-meaning, if remarkably incompetent, rescue attempts by neighbours. Eventually they all blur into one in Tiddles' mind, just as they have for every parent who has found themselves watching those episodes for the 20th time. As he stares directly into the camera, the viewer is left to contemplate whether there isn't a little bit of Tiddles in all of us.

Only one option remains open to Tiddles: he must wait out Dr Hamster until she dies, and he is finally free. Back in his box, Tiddles settles in to play the Longest Game.

## Putting up a picture

An actual Peppa Pig episodes I never tire of.

In which Daddy Pig is given a task and messes it up, but then he brings his A-game to fixing it and covering his tracks before his wife finds out. 10/10 husband skills.

## Carrots

Carrots, SQUEAK! Rebecca Rabbit and her family love carrots. Carrots for breakfast, carrots for lunch, carrots for dinner. Yum!
Alas, carrots are full of sugar, and feeding rabbits too many carrots is a great way to give them diabetes.
This point is explained with some urgency to Mummy Rabbit and Mr Rabbit as a severely malnourished Rebecca Rabbit is rushed to hospital.


## Der Untergang

*(Because it turns out that the guy who does the voice for Mr Pony in the German version of Peppa Pig sounds just like Bruno Ganz as Hitler in 'Downfall'.)*

Mr Pony in a bunker screaming at Daddy Pig, Mr Bull and Dr Brown Bear, all in full Wehrmacht uniform, for cowardice after learning that Miss Rabbit has failed to repel an attack by enemy squirrels (red squirrels, presumably).

Later, Mr Pony awards a medal to Peppa and her friends who took out a soviet tank with an anti-tank gun. Peppa loves the Panzerfaust 150. Everybody loves the Panzerfaust 150!

## Bonus! A Paw Patrol episode I’d like to see

*At some point your children decide they are too big for Peppa. Initially this feels like blessed relief, until you realise they are simply moving on to a deeper level of abject gibberish (I'm looking at you Paw Patrol).*

Ryder’s pup pad bleeps - its Mr Porter from the cafe.

“Hi Mr Porter! Do you have an emergency?”

“Help Ryder! There’s trash all over the road, and a swarm of bees keep scaring away my customers!”

“Oh…” sighs Ryder. “Don’t you think you could maybe, like, sort that out yourself?
It sounds like all you need is some bin bags and to call a pest removal company rather than us.”
Mr Porter looks obviously flummoxed, which on reflection ought not to be unusual for a man who once let penguins eat his entire stock.

“Also, to be totally frank,” continues Ryder, “I’ve got an absolute beast of a hangover, and the pups are halfway through a big shop at Asda, so it’s not great timing.”

“Oh, er, well I guess so…” mumbles Mr Porter.

“That’s the spirit. Remember, if you’re ever in trouble, just yelp for help! On the other hand, if it’s just a bit of a tedious nuisance, sort it yourself.”
